name: Tech Hobo
favicon: null
layout_spectrum: 0.25042
typography_spectrum: 0.4398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00c6ff'
    - '#ffffff'
    - '#868686'
    - '#414141'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
